### ISSUE TITLE
read/resolve hierarchy

### ISSUE THREAD

**Issue by drewboswell** [drewboswell/converge#13]

**Comment by drewboswell** [comment]
Example hierarchy; application first approach with separate shared usage
```
# last hit wins
# shared configurations
- default/shared
- default/shared/environment/${environment}
- default/shared/environment/${environment}/${app}
- default/shared/pool/${pool}
- default/shared/pool/${pool}/${app}
- default/shared/host/${host}
- default/shared/host/${host}/${app}
# application centric overrides
- default/app/${app}
- default/app/${app}/environment/${environment}
- default/app/${app}/environment/${environment}/${app}
- default/app/${app}/pool/${pool}
- default/app/${app}/pool/${pool}/${app}
- default/app/${app}/host/${host}
- default/app/${app}/host/${host}/${app}
```

**Comment by drewboswell** [comment]
Example hierarchy; application first approach with shared repositories as application sub-repositories usage
```
# last hit wins
# shared configurations
- default/app/${app}/shared
- default/app/${app}/shared/environment/${environment}
- default/app/${app}/shared/environment/${environment}/${app}
- default/app/${app}/shared/pool/${pool}
- default/app/${app}/shared/pool/${pool}/${app}
- default/app/${app}/shared/host/${host}
- default/app/${app}/shared/host/${host}/${app}
# application centric overrides
- default/app/${app}
- default/app/${app}/environment/${environment}
- default/app/${app}/environment/${environment}/${app}
- default/app/${app}/pool/${pool}
- default/app/${app}/pool/${pool}/${app}
- default/app/${app}/host/${host}
- default/app/${app}/host/${host}/${app}
```

**Comment by drewboswell** [comment]
possible data structure after reading hierarchy yaml file:
```
hierarchy:
   - hiera: $full_string
     regex: $pcre_hiera_math
     tags: $tags_in_string
```
**Simple Example**
*simple hierarchy with one layer*
```
- default/app/${app}/environment/${environment}
```
*resolved in the data structure*
```
hierarchy:
   - hiera: "default/app/${app}/environment/${environment}"
     regex: "default/app/([^/]+)/environment/([^/]+)"
     tags: 
        - "app"
        - "environment"
```

**Comment by drewboswell** [comment]
yaml file should be checked for doubles, and structure.

*Package yaml schema for validation*
```
type: seq
sequence:
  - type: str
    unique: True
```
