### ISSUE TITLE
read/resolve configuration file (converge.ini)

### ISSUE THREAD

**Issue by drewboswell** [drewboswell/converge#19]

**Comment by drewboswell** [comment]
this has been changed to yaml to allow multiple dimensions of configuration, versus the properties style ini two dimentional definitions.

converge.yaml is now the configuration file

**Comment by drewboswell** [comment]
example configuration file as committed a couple of times in tests, a possible yaml spec can be:

`# Package yaml schema for validation
type: map
mapping:
  default:
    type: map
    mapping:
      logging_level:
        type: str
        enum: ['INFO', 'DEBUG', 'WARN', 'ERROR', 'CRITICAL','FATAL']
  programs:
    type: map
    mapping:
      regex;(^.*$):
        type: map
        mapping:
          conf:
            type: map
            mapping:
              regex;(^.*$):
                type: any
          instructions:
            type: seq
            matching: "any"
            sequence:
              - type: map
                matching-rule: any
                mapping:
                  regex;(^(read_data|write|validate|read_hierarchy|resolve)$):
                    type: seq
                    matching: any
                    sequence:
                      - type: str
                      - type: map
                        mapping:
                          regex;(^.*$):
                            type: map
                            mapping:
                              filter:
                                type: seq
                                sequence:
                                  - type: str
`

**Comment by drewboswell** [comment]
the idea is that you pass class-paths to the read/resolve/filter/writer blocks that are then run on the same datasets.

example for properties resolutions:
```
default:
  logging_level: "INFO"
programs:
  properties:
    conf:
      yaml:
        base_dir: "repository"
        schema_path: "schemas"
        hierarchy_path: "hierarchy.yaml"
      properties:
        base_dir: "repository"
        hierarchy_path: "hierarchy.yaml"
        host_glob: "targets/hosts/**/*.yaml"
        mapping_glob: "targets/mapping/**/*.yaml"
        dependency_glob: "data/**/dependencies.properties"
        properties_glob: "data/**/*.properties"
        output_dir: "output"
    instructions:
      - validate:
        - "pyconverge.plugins.yaml.Hierarchy.Validator"
        - "pyconverge.plugins.yaml.Targets.Validator"
      - read_hierarchy:
        - "pyconverge.plugins.yaml.Hierarchy.Hierarchy"
      - read_data:
        - "pyconverge.plugins.properties.PropertiesFinder.PropertiesFinder":
            filter:
              - "pyconverge.plugins.properties.PropertiesFilters.ReadFilter"
      - resolve:
        - "pyconverge.plugins.properties.PropertiesResolver.PropertiesResolver"
      - write:
        - "pyconverge.plugins.properties.PropertiesWriter.PropertiesWriter":
            filter:
              - "pyconverge.plugins.placeholder.PlaceholderFilters.PlaceholderFilter"

```
